name:                hello-rio
version:             0.1.0.0
github:              githubuser/hello-rio
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/hello-rio#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.8.0
- HUnit >= 1.6.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hello-rio-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - hello-rio
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  hello-rio-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hello-rio
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
